bullseye/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('bullseyeapp.urls')),
    path('admin/', admin.site.urls),
    path('oauth/', include('social_django.urls', namespace='oauth'))
]

bullseyeapp/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.get_landing_page, name='landing_page'),
    path('wikiprefs', views.update_wiki_prefs, name='update_wiki_prefs'),
    path('logout', views.logout_view, name='logout'),
    path('dartboard', views.dartboard, name='dartboard'),
    path('ip/<str:ip>', views.render_ip_info, name='ip'),
    path('ip/<str:ip>/<int:cidr>', views.get_ip_range_info),
    path('api/ip/<str:ip>', views.rest_ip_info),
    path('api/bulk_ip', views.rest_bulk_ip_info)
]

bullseyeapp/models.py
import datetime

from django.contrib.auth.models import User
from django.db import models
from django.db.models import UniqueConstraint
from django.utils import timezone
from picklefield.fields import PickledObjectField

class MonthlyStats(models.Model):
    name = models.CharField(null=False, blank=False, max_length=255)
    month = models.DateField(default=timezone.now().date().replace(day=1))
    count = models.IntegerField(default=0)

    unique_name_month = UniqueConstraint(name='unique_name_month', fields=['name', 'month'])

    def __str__(self):
        return f'{self.name} {self.month.month}/{self.month.year}: {self.count}'

    class Meta:
        verbose_name = 'Monthly Stats'
        verbose_name_plural = 'Monthly Stats'


class UserRight(models.Model):
    name = models.TextField()
    stats = models.ManyToManyField(MonthlyStats)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'User Right'
        verbose_name_plural = 'User Rights'


class ExtraUserData(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    userrights = models.ManyToManyField(UserRight)
    targetwikis = PickledObjectField()
    last_updated = models.DateTimeField(auto_now=True)
    stats = models.ManyToManyField(MonthlyStats)

    def __str__(self):
        return self.user.username

    class Meta:
        verbose_name = 'Extra User Data'
        verbose_name_plural = 'Extra User Data'

bullseyeapp/forms.py
from django import forms

class WikiForm(forms.Form):
    wikis = forms.MultipleChoiceField(label='Wiki blocks')
    def __init__(self, choices=None, *args, **kwargs):
        super(WikiForm, self).__init__(*args, **kwargs)
        if choices:
            self.fields['wikis'].choices = choices

bullseyeapp/views.py
import ipaddress

from deepmerge import always_merger
from multiprocessing.pool import ThreadPool

from django.conf import settings
from django.contrib.auth import logout
from django.db.models import Q
from django.http import JsonResponse
from django.shortcuts import redirect, render
from django.views.decorators.http import require_http_methods
from rest_framework.decorators import api_view, permission_classes
from rest_framework.response import Response
from rest_framework import permissions
from rest_framework.authtoken.models import Token

from . import forms
from . import utils
from .models import ExtraUserData


def get_landing_page(request):
    return render(request, 'bullseye/index.html')

@require_http_methods(['GET', 'POST'])
def dartboard(request):
    if request.method == 'GET':
        return render(request, 'bullseye/dartboard.html')
    # guaranteed to be POST now
    context = {}
    context['cdnjs'] = settings.CDNJS
    if hasattr(settings, 'MAPSERVER') and settings.MAPSERVER:
        context['mapserver'] = settings.MAPSERVER
    form_data = request.POST
    geos = []
    ips, errors = utils.parse_ip_form(form_data['dartboardIPs'])
    for ip in ips:
        if hasattr(settings, 'GEOIP_PATH') and settings.GEOIP_PATH:
            geos.append(utils.lookup_maxmind_dartboard(ip))

    context['geoips'] = {
        'type': 'FeatureCollection',
        'features': geos
    }
    context['ips'] = ips
    context['errors'] = errors
    return render(request, 'bullseye/dartboard-map.html', context)

def get_ip_info(request, ip):
    context = {}
    context['ip'] = ip
    context['data_sources'] = {}
    context['geoips'] = {
        'type': 'FeatureCollection',
        'features': []
    }

    with ThreadPool() as pool:
        queries = []
        # TODO: cache this in the User model somehow
        userrights_query = pool.apply_async(utils.get_userrights, (request.user,))

        queries.append(pool.apply_async(utils.get_whois_data, (ip,)))
        queries.append(pool.apply_async(utils.get_maxmind_data, (ip,)))
        queries.append(pool.apply_async(utils.get_rdns, (ip,)))
        queries.append(pool.apply_async(utils.get_ipcheck_data, (ip,)))
        queries.append(pool.apply_async(utils.get_bgpview_data, (ip,)))
    
        # Need the wiki query to finish to get the target wikis and access rights
        userrights_ctx = userrights_query.get()
        always_merger.merge(context, userrights_ctx)
        if 'usergroups' in request.session and request.session['usergroups']:
            usergroups = request.session['usergroups']
        else:
            userdata = ExtraUserData.objects.get(user=request.user)
            usergroups = []
            # Convert to list - we can't serialize userdata as-is
            for group in userdata.userrights.all():
                usergroups.append(group.name)
            request.session['usergroups'] = usergroups
        queries.append(pool.apply_async(utils.get_relevant_blocks, (ip, context['targetwikis'])))
    
        if 'steward' in usergroups or 'checkuser' in usergroups or 'staff' in usergroups or \
                request.user.groups.filter(name='trusted').count():
            queries.append(pool.apply_async(utils.get_spur_data, (ip,)))
    
        if 'steward' in usergroups or 'checkuser' in usergroups or 'staff' in usergroups or 'sysop' in usergroups or 'global-sysop' in usergroups or \
                request.user.groups.filter(name='trusted').count():
            queries.append(pool.apply_async(utils.get_shodan_data, (ip,)))

        for query in queries:
            query_ctx = query.get()
            always_merger.merge(context, query_ctx)

    utils.increment_user_queries(request.user)
    return context

def render_ip_info(request, ip):
    if not request.user.is_authenticated:
        return render(request, 'bullseye/notauthed.html')
    context = get_ip_info(request, ip)
    context['cdnjs'] = settings.CDNJS
    if hasattr(settings, 'MAPSERVER') and settings.MAPSERVER:
        context['mapserver'] = settings.MAPSERVER
    return render(request, 'bullseye/ip.html', context)

@api_view(['GET'])
@permission_classes([permissions.IsAuthenticated])
def rest_ip_info(request, ip):
    context = get_ip_info(request, ip)
    # sanitize - don't give people the full shodan dump
    if 'shodan' in context and 'data' in context['shodan']:
        del context['shodan']['data']
    return Response(context)


@api_view(['POST'])
@permission_classes([permissions.IsAuthenticated])
def rest_bulk_ip_info(request):
    if not request.user.is_authenticated:
        return render(request, 'bullseye/notauthed.html')
    ret = {}
    for ip in request.POST:
        context = get_ip_info(request, ip)
        # sanitize - don't give people the full shodan dump
        if 'shodan' in context and 'data' in context['shodan']:
            del context['shodan']['data']
        ret[ip] = context
    return Response(ret)

def get_ip_range_info(request, ip, cidr):
    if not request.user.is_authenticated:
        return render(request, 'bullseye/notauthed.html')
    context = {}
    context['searched_range'] = ip + '/' + str(cidr)
    context['ip'] = ip
    context['data_sources'] = {}
    context['geoips'] = {
        'type': 'FeatureCollection',
        'features': []
    }

    with ThreadPool() as pool:
        queries = []
        # TODO: cache this in the User model somehow
        userrights_query = pool.apply_async(utils.get_userrights, (request.user,))

        queries.append(pool.apply_async(utils.get_whois_data, (ip,)))
        queries.append(pool.apply_async(utils.get_maxmind_data, (ip,)))
        queries.append(pool.apply_async(utils.get_rdns, (ip,)))
        queries.append(pool.apply_async(utils.get_ipcheck_data, (ip,)))
        queries.append(pool.apply_async(utils.get_bgpview_data, (ip,)))
    
        # Need the wiki query to finish to get the target wikis and access rights
        userrights_ctx = userrights_query.get()
        always_merger.merge(context, userrights_ctx)
        if 'usergroups' in request.session and request.session['usergroups']:
            usergroups = request.session['usergroups']
        else:
            userdata = ExtraUserData.objects.get(user=request.user)
            usergroups = []
            # Convert to list - we can't serialize userdata as-is
            for group in userdata.userrights.all():
                usergroups.append(group.name)
            request.session['usergroups'] = usergroups
        queries.append(pool.apply_async(utils.get_relevant_blocks, (ip, context['targetwikis'])))
    
        if 'steward' in usergroups or 'checkuser' in usergroups or 'staff' in usergroups or 'accountcreator' in usergroups or \
                request.user.groups.filter(name='trusted').count():
            queries.append(pool.apply_async(utils.get_spur_data, (ip,)))
    
        if 'steward' in usergroups or 'checkuser' in usergroups or 'staff' in usergroups or 'sysop' in usergroups or 'global-sysop' in usergroups or 'accountcreator' in usergroups or\
                request.user.groups.filter(name='trusted').count():
            queries.append(pool.apply_async(utils.get_shodan_data, (ip,)))

        for query in queries:
            query_ctx = query.get()
            always_merger.merge(context, query_ctx)

        
    utils.increment_user_queries(request.user)
    context['cdnjs'] = settings.CDNJS
    if hasattr(settings, 'MAPSERVER') and settings.MAPSERVER:
        context['mapserver'] = settings.MAPSERVER
    return render(request, 'bullseye/ip_range.html', context)

@require_http_methods(['GET', 'POST'])
def update_wiki_prefs(request):
    if not request.user.is_authenticated:
        return render(request, 'bullseye/notauthed.html')
    sitematrix = utils.get_sitematrix()
    sites_grouped = {}
    valid_sites = []
    for entry in sitematrix['sitematrix']:
        if entry in ['specials', 'count']:
            continue
        for site in sitematrix['sitematrix'][entry]['site']:
            if 'closed' in site or 'private' in site or 'fishbowl' in site:
                continue
            if not site['code'] in sites_grouped:
                sites_grouped[site['code']] = []
            sites_grouped[site['code']].append((site['dbname'], site['dbname']))
            valid_sites.append(site['dbname'])

    sites_grouped['special'] = []
    for site in sitematrix['sitematrix']['specials']:
        if 'closed' in site or 'private' in site or 'fishbowl' in site:
            continue
        sites_grouped['special'].append((site['dbname'], site['dbname']))
        valid_sites.append(site['dbname'])
    sites = []
    for k,v in sites_grouped.items():
        sites.append((k, v))
    userrights = utils.get_userrights(request.user)
    if request.method == 'POST':
        form = forms.WikiForm(data=request.POST, choices=sites, initial={'wikis': list(userrights['targetwikis'])})
        if form.is_valid():
            print(form.cleaned_data)
            print(form.cleaned_data['wikis'])
            userdata = ExtraUserData.objects.get(user=request.user)
            userdata.targetwikis = form.cleaned_data['wikis']
            userdata.save()
            return redirect(get_landing_page)
    else:
        # Doing this to force default group creation if needed
        form = forms.WikiForm(choices=sites, initial={'wikis': list(userrights['targetwikis'])})
    token = Token.objects.get_or_create(user=request.user)[0]
    return render(request, 'bullseye/wikiprefs.html', {'form': form, 'cdnjs': settings.CDNJS, 'token': token.key})

def logout_view(request):
    logout(request)
    return redirect(get_landing_page)

bullseyeapp/templates/bullseye/base.html
{% extends 'bullseye/bootstrap.html' %}

{% load bootstrap5 %}
{% load static %}

{% block bootstrap5_extra_head %}
<link rel="shortcut icon" type="image/svg" href="{% static 'bullseye/logo.svg' %}"/>
{% endblock %}

{% block bootstrap5_content %}
  <div class="container">
    <nav class="navbar navbar-expand-lg navbar-dark bg-secondary">
      <span class="navbar-brand mx-2">
        <img src="{% static 'bullseye/logo.svg' %}" alt="bullseye logo" width="50" height="50"/>
      </span>
      <span class="nav-item dropdown">
        <a class="nav-link dropdown-toggle text-light" href="#" id="navbarToolsDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
          Tools
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarToolsDropdown">
	  <a class="dropdown-item" href="{% url "landing_page" %}">Bullseye</a>
	  <a class="dropdown-item" href="{% url "dartboard" %}">Dartboard</a>
        </div>
      </span>
      <form class="d-flex" onsubmit="return doSearchNav()">
        <div class="form-group">
          <input type="text" class="form-control" id="inputIPNav" placeholder="IP address">
        </div>
        <button id="submitBtnNav" type="submit" class="btn btn-primary ms-2">Search</button>
      </form>
      <span class="nav-item dropdown ms-auto mx-2">
        <a class="nav-link dropdown-toggle text-light" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
          {% if user.is_authenticated %}
          Logged in as {{ user.username }}
          {% else %}
          Not logged in
          {% endif %}
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          {% if user.is_authenticated %}
	  <a class="dropdown-item" href="{% url "logout" %}?next={{ request.path }}">Log out</a>
	  <a class="dropdown-item" href="{% url "update_wiki_prefs" %}">Set preferences</a>
          {% else %}
	  <a class="dropdown-item" href="{% url "social:begin" "mediawiki"%}?next={{ request.path }}">Log in</a>
          {% endif %}
          {% if user.is_staff %}
	  <a class="dropdown-item" href="{% url "admin:index" %}">Admin</a>
          {% endif %}
        </div>
      </span>
    </nav>
    <h1>{% block title %}(no title){% endblock %}</h1>

    {% autoescape off %}{% bootstrap_messages %}{% endautoescape %}

    {% block content %}(no content){% endblock %}
  </div>
<div class="container my-5">
    <div class="text-center text-secondary bg-white">
      Bullseye by [[<a href="https://en.wikipedia.org/wiki/User:GeneralNotability">User:GeneralNotability</a>]]
    </div>
    <div class="text-center text-secondary bg-white">
      Logo by [[<a href="https://en.wikipedia.org/wiki/User:Giraffer">User:Giraffer</a>]]
    </div>
    <div class="text-center text-secondary bg-white">
      <a href="https://github.com/GeneralNotability/bullseye">Source</a>
    </div>
    <!-- Copyright -->
  </footer>

  <script>
    function doSearchNav() {
      const ip = document.getElementById("inputIPNav").value;
      window.location = '/ip/' + ip;
      return false;
    }
  </script>
{% endblock %}

bullseyeapp/templates/bullseye/bootstrap.html
{% extends 'bootstrap5/bootstrap5.html' %}

{% block bootstrap5_title %}{% block title %}{% endblock %}{% endblock %}

bullseyeapp/templates/bullseye/dartboard-map.html
{% extends 'bullseye/base.html' %}
{% load bootstrap5 %}


{% block title %}
Dartboard
{% endblock %}


{% block content %}
{% if mapserver %}
{% if geoips.features %}
<p>IPs: {{ ips }}</p>
{% include 'bullseye/map.html' %}
{% else %}
<h3>No valid IPs were specified, no data sources were available, or none of the IPs had geolocation information</h3>
{% endif %}
{% else %}
<h2>This feature requires a map server.</h2>
{% endif %}

{% endblock %}

bullseyeapp/templates/bullseye/dartboard.html
{% extends 'bullseye/base.html' %}
{% load bootstrap5 %}


{% block title %}
Dartboard
{% endblock %}


{% block content %}
<form action="" method="post" id="dartboard">
  <div class="form-group">
    <textarea class="form-control" id="dartboardIPs" aria-describedby="ipHelp" placeholder="IPs" name="dartboardIPs" required></textarea>
    <small id="ipHelp" class="form-text text-muted">IP addresses, one per line.</small>
    {% csrf_token %}
  </div>
  <button id="submitBtn" type="submit" class="btn btn-primary">Search</button>
</form>

{% endblock %}

bullseyeapp/templates/bullseye/index.html
{% extends 'bullseye/base.html' %}
{% load bootstrap5 %}


{% block title %}
Bullseye
{% endblock %}


{% block content %}
<form onsubmit="return doSearch()">
  <div class="form-group">
    <label for="inputIP">IP Address</label>
    <input type="text" class="form-control" id="inputIP" aria-describedby="ipHelp" placeholder="IP">
    <small id="ipHelp" class="form-text text-muted">IP address to look up.</small>
  </div>
  <button id="submitBtn" type="submit" class="btn btn-primary">Search</button>
</form>

<script>
function doSearch() {
    const ip = document.getElementById("inputIP").value;
    window.location = '/ip/' + ip;
    return false;
}
</script>

{% endblock %}

bullseyeapp/templates/bullseye/ip.html
{% extends 'bullseye/base.html' %}
{% load bootstrap5 %}


{% block title %}
{{ ip }}
{% endblock %}


{% block content %}

<p>Range: {{ range|default:'unknown' }}<br />
Location: {{ location|default:'unknown' }}<br />
Hostname: {{ rdns|default:'unknown' }}<br />
ISP: {{ isp|default:'unknown' }}</p>
{% if mapserver %}
{% include 'bullseye/map.html' %}
{% endif %}

<div class="accordion">
{% include 'bullseye/data_components/blocks.html' %}
{% if data_sources.whois %}
  {% include 'bullseye/data_components/whois.html' %}
{% endif %}
{% if data_sources.maxmind %}
  {% include 'bullseye/data_components/maxmind.html' %}
{% endif %}
{% if data_sources.ipcheck %}
  {% include 'bullseye/data_components/ipcheck.html' %}
{% endif %}
{% if data_sources.spur %}
  {% include 'bullseye/data_components/spur.html' %}
{% endif %}
{% if data_sources.shodan %}
  {% include 'bullseye/data_components/shodan.html' %}
{% endif %}
{% if data_sources.bgpview %}
  {% include 'bullseye/data_components/bgpview.html' %}
{% endif %}
</div>
{% endblock %}

bullseyeapp/templates/bullseye/ip_range.html
{% extends 'bullseye/base.html' %}
{% load bootstrap5 %}


{% block title %}
{{ searched_range }}
{% endblock %}


{% block content %}

<p>Range: {{ range|default:'unknown' }}<br />
Location: {{ location|default:'unknown' }}<br />
Hostname: {{ rdns|default:'unknown' }}<br />
ISP: {{ isp|default:'unknown' }}</p>
{% if mapserver %}
{% include 'bullseye/map.html' %}
{% endif %}

<div class="accordion">
{% include 'bullseye/data_components/blocks.html' %}
{% if data_sources.whois %}
  {% include 'bullseye/data_components/whois.html' %}
{% endif %}
{% if data_sources.maxmind %}
  {% include 'bullseye/data_components/maxmind.html' %}
{% endif %}
{% if data_sources.ipcheck %}
  {% include 'bullseye/data_components/ipcheck.html' %}
{% endif %}
{% if data_sources.spur %}
  {% include 'bullseye/data_components/spur.html' %}
{% endif %}
{% if data_sources.shodan %}
  {% include 'bullseye/data_components/shodan.html' %}
{% endif %}
{% if data_sources.bgpview %}
  {% include 'bullseye/data_components/bgpview.html' %}
{% endif %}
</div>
{% endblock %}

bullseyeapp/templates/bullseye/map.html
{% block bootstrap5_extra_head %}
<meta name="referrer" content="strict-origin-when-cross-origin" />
<link rel="stylesheet" href="{{ cdnjs }}/ajax/libs/leaflet/1.7.1/leaflet.css" />
{% endblock %}

<script src="{{ cdnjs }}/ajax/libs/leaflet/1.7.1/leaflet.js"></script>
<div id='map' width="100%" style='height:400px'></div>
<script>
    function popup(feature, layer) {
        if (feature.properties && feature.properties.description) {
            layer.bindPopup(feature.properties.description);
        }
    }
    let ipLocGeoJSON = {{ geoips|safe }};
    let server = '{{ mapserver }}';
    let style = 'osm-intl';
    let map = L.map('map');
    if (ipLocGeoJSON.features.length > 0) {
        let bounds = L.latLngBounds(ipLocGeoJSON.features.map((c) => {
            return [c.geometry.coordinates[1], c.geometry.coordinates[0]]
        }));
        map.fitBounds(bounds, {maxZoom: 8});
    } else {
        // Fallback if there's no geolocation
        map.setView([0, 0], 3);
    }
    L.tileLayer(server + '/' + style + '/{z}/{x}/{y}{r}.png').addTo(map);
    L.control.scale().addTo(map);
    map.whenReady(() => {
      L.geoJson(ipLocGeoJSON, {onEachFeature: popup}).addTo(map);
    });
</script>

bullseyeapp/templates/bullseye/notauthed.html
{% extends 'bullseye/base.html' %}
{% load bootstrap5 %}


{% block title %}
Not authenticated
{% endblock %}


{% block content %}
<h2>You must log in with your Wikimedia account to use this site.</h2>
{% endblock %}

bullseyeapp/templates/bullseye/wikiprefs.html
{% extends 'bullseye/base.html' %}
{% load bootstrap5 %}

{% block bootstrap5_extra_head %}
<script type="text/javascript" src="{{ cdnjs }}/ajax/libs/jquery/3.6.0/jquery.min.js"></script>

<script type="text/javascript" src="{{ cdnjs }}/ajax/libs/bootstrap-multiselect/1.1.1/js/bootstrap-multiselect.js"></script>
<link rel="stylesheet" href="{{ cdnjs }}/ajax/libs/bootstrap-multiselect/1.1.1/css/bootstrap-multiselect.min.css"/>
{% endblock %}

{% block title %}
Bullseye
{% endblock %}


{% block content %}
<form action="" method="post" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" value="submit">
</form>
API Token: {{ token }}
<script type="text/javascript">
    $(document).ready(function() {
        $('#id_wikis').multiselect({
            buttonClass: 'form-select',
            buttonWidth: '75%',
            enableFiltering: true,
            enableCollapsibleOptGroups: true,
            widthSynchronizationMode: 'always',
            numberDisplayed: 0,
            templates: {
                button: '<button type="button" class="multiselect dropdown-toggle" data-bs-toggle="dropdown"><span class="multiselect-selected-text"></span></button>',
            }
        });
        document.forms['MarkerForm'].reset();
    });
</script>
{% endblock %}